DROP TABLE IF EXISTS testtable;

CREATE TABLE IF NOT EXISTS testtable(
    testid INT AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(255) NOT NULL,
    lname VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL,
);
